name: "Check secrets"
on: push

env: 
  GBL_ENV: "this is global env var"

jobs: 
  see-log:
    runs-on: ubuntu-latest
    name: "see global var"
    env:
      JOB_ENV: "this is job env var"
    steps: 
      - name: 'see logs'
        env:
          STEP_ENV: "this is step env var"
        run: |
          echo "GBL_ENV: ${GBL_ENV}"
          echo "JOB_ENV: ${JOB_ENV}"
          echo "STEP_ENV: ${STEP_ENV}"

